import { useState } from 'react';
import Head from 'next/head';
import QuestionsList from '../sections/QuestionsList';
import LightDarkToggler from '../components/LightDarkToggler';

import styles from '../styles';

export default function Home({ data }) {
  const [isDark, setIsDark] = useState(false);

  return (
    <div className={isDark ? 'dark' : null}>
      <div
        className={`${styles.flexCenter} items-start pt-20 dark:bg-gray-900 relative min-h-screen overflow-hidden px-[30px] bg-[#F5F7FB] transition-all`}
      >
        <Head>
          <title>Quizzical App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="background-01 z-0 -m-[90px] lg:m-0" />
        <div className="background-02 z-0 -my-[90px] lg:m-0" />
        <LightDarkToggler
          isDark={isDark}
          toggleDark={() => (setIsDark((curVal) => !curVal))}
        />
        <main
          className={`${styles.fonts.inter} relative z-10 text-[3rem] w-fit max-w-[400px] md:max-w-[600px] lg:max-w-[800px] mx-auto pb-8 md:pb-[25px]`}
        >
          <QuestionsList data={data} />
        </main>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch('https://opentdb.com/api.php?amount=30&category=9&type=multiple');
  const data = await res.json();

  return {
    props: { data: data.results },
  };
}
