export default [
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'easy',
    question: 'What was the name of the WWF professional wrestling tag team made up of the wrestlers Ax and Smash?',
    correct_answer: 'Demolition',
    incorrect_answers: [
      'The Dream Team',
      'The Bushwhackers',
      'The British Bulldogs',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'easy',
    question: 'Area 51 is located in which US state?',
    correct_answer: 'Nevada',
    incorrect_answers: [
      'Arizona',
      'New Mexico',
      'Utah',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'hard',
    question: 'What is the airspeed velocity of an unladen swallow?',
    correct_answer: '24 MPH',
    incorrect_answers: [
      '15 MPH',
      '20 MPH',
      '200 MPH',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'easy',
    question: 'Which sign of the zodiac is represented by the Crab?',
    correct_answer: 'Cancer',
    incorrect_answers: [
      'Libra',
      'Virgo',
      'Sagittarius',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'medium',
    question: 'In the Morse code, which letter is indicated by 3 dots? ',
    correct_answer: 'S',
    incorrect_answers: [
      'O',
      'A',
      'C',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What does the &quot;G&quot; mean in &quot;G-Man&quot;?',
    correct_answer: 'Government',
    incorrect_answers: [
      'Going',
      'Ghost',
      'Geronimo',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Which essential condiment is also known as Japanese horseradish?',
    correct_answer: 'Wasabi ',
    incorrect_answers: [
      'Mentsuyu',
      'Karashi',
      'Ponzu',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What is the name of the very first video uploaded to YouTube?',
    correct_answer: 'Me at the zoo',
    incorrect_answers: [
      'tribute',
      'carrie rides a truck',
      'Her new puppy from great grandpa vern.',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'hard',
    question: 'Before the 19th Century, the &quot;Living Room&quot; was originally called the...',
    correct_answer: 'Parlor',
    incorrect_answers: [
      'Open Room',
      'Sitting Room',
      'Loft',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'hard',
    question: 'Which of the following chemicals are found in eggplant seeds?',
    correct_answer: 'Nicotine',
    incorrect_answers: [
      'Mescaline',
      'Cyanide',
      'Psilocybin',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'hard',
    question: 'Which of these banks are NOT authorized to issue currency notes in Hong Kong?',
    correct_answer: 'OCBC',
    incorrect_answers: [
      'HSBC',
      'Standard Chartered',
      'Bank of China',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'easy',
    question: 'What was the nickname given to the Hughes H-4 Hercules, a heavy transport flying boat which achieved flight in 1947?',
    correct_answer: 'Spruce Goose',
    incorrect_answers: [
      'Noah&#039;s Ark',
      'Fat Man',
      'Trojan Horse',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What is the romanized Japanese word for &quot;university&quot;?',
    correct_answer: 'Daigaku',
    incorrect_answers: [
      'Toshokan',
      'Jimusho',
      'Shokudou',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'medium',
    question: 'According to the United States&#039; CDC, one in how many Americans die annually due to smoking?',
    correct_answer: 'Five',
    incorrect_answers: [
      'Twenty',
      'Ten',
      'One hundred',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'easy',
    question: 'Which one of these is not a typical European sword design?',
    correct_answer: 'Scimitar',
    incorrect_answers: [
      'Falchion',
      'Ulfberht',
      'Flamberge',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'easy',
    question: 'What is the name of Poland in Polish?',
    correct_answer: 'Polska',
    incorrect_answers: [
      'Pupcia',
      'Polszka',
      'P&oacute;land',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'medium',
    question: 'When did the website &quot;Facebook&quot; launch?',
    correct_answer: '2004',
    incorrect_answers: [
      '2005',
      '2003',
      '2006',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Which slogan did the fast food company, McDonald&#039;s, use before their &quot;I&#039;m Lovin&#039; It&quot; slogan?',
    correct_answer: 'We Love to See You Smile',
    incorrect_answers: [
      'Why Pay More!?',
      'Have It Your Way',
      'Making People Happy Through Food',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'hard',
    question: 'In flight systems, what does the initialism &quot;TCAS&quot; stand for?',
    correct_answer: 'Traffic Collision Avoidance System',
    incorrect_answers: [
      'Traffic Communication Alert System',
      'Traffic Configuration Alignment System',
      'Traffic Call-sign Abbreviation System',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Whose greyscale face is on the kappa emoticon on Twitch?',
    correct_answer: 'Josh DeSeno',
    incorrect_answers: [
      'Justin DeSeno',
      'John DeSeno',
      'Jimmy DeSeno',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'hard',
    question: 'Originally another word for poppy, coquelicot is a shade of what?',
    correct_answer: 'Red',
    incorrect_answers: [
      'Green',
      'Blue',
      'Pink',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'easy',
    question: 'In which fast food chain can you order a Jamocha Shake?',
    correct_answer: 'Arby&#039;s',
    incorrect_answers: [
      'McDonald&#039;s',
      'Burger King',
      'Wendy&#039;s',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'hard',
    question: 'Where is Apple Inc. headquartered?',
    correct_answer: 'Cupertino, California',
    incorrect_answers: [
      'Redwood City, California',
      'Redmond, Washington',
      'Santa Monica, CA',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What is the star sign of someone born on Valentines day?',
    correct_answer: 'Aquarius',
    incorrect_answers: [
      'Pisces',
      'Capricorn',
      'Scorpio',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'easy',
    question: 'When one is &quot;envious&quot;, they are said to be what color?',
    correct_answer: 'Green',
    incorrect_answers: [
      'Red',
      'Blue',
      'Yellow',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'hard',
    question: 'The word &quot;abulia&quot; means which of the following?',
    correct_answer: 'The inability to make decisions',
    incorrect_answers: [
      'The inability to stand up',
      'The inability to concentrate on anything',
      'A feverish desire to rip one&#039;s clothes off',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'easy',
    question: 'Foie gras is a French delicacy typically made from what part of a duck or goose?',
    correct_answer: 'Liver',
    incorrect_answers: [
      'Heart',
      'Stomach',
      'Intestines',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Directly between the Washington Monument and the Reflecting Pool is a memorial to which war?',
    correct_answer: 'World War II',
    incorrect_answers: [
      'Vietnam War',
      'American Civil War',
      'American Revolutionary War',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What fast food chain has the most locations globally? ',
    correct_answer: 'Subway',
    incorrect_answers: [
      'Starbucks',
      'McDonalds',
      'KFC',
    ],
  },
  {
    category: 'General Knowledge',
    type: 'multiple',
    difficulty: 'hard',
    question: 'In &quot;Resident Evil 3&quot;, how many inventory slots does Jill have at the start of the game?',
    correct_answer: '10',
    incorrect_answers: [
      '6',
      '8',
      '12',
    ],
  },
];
